version: "3.9"

services:
  db-postgres:
    image: postgres:15
    container_name: db-postgres
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
